### ISSUE TITLE
problems provisioning kinesis

### ISSUE THREAD

**Issue by mmodenesi** [MrWormHole/hotdog-localstack-PoC#1]
Hey! great article, thanks for sharing your knowledge.

I tried to follow instructions and I found these problems, maybe you can help me and this may be useful for future readers:

1) on ubuntu, using docker bridged network, mapping port "53:53" conflicts with systemd-resolved which uses that port (so docker-compose up fails altoghether). I solved this (i think) using my local IP on docker-compose.yml, as in "- "192.160.0.13:53:53"

2) when provisioning kinesis streams terraform apply will fail. It just hangs. Logs on local_stack show that kinesis exits with code=1, not very helpful. I could not solve this problem. I am using `localstack/localstack   latest             5282bc09953a` image.

3) I cannot see anything on localhost:8080, is localstack pro suscription required? (sorry, I am new to localstack).

Thanks, again!

**Comment by occamist** [comment]
Hi! No problem. 

53:53 mapping is no longer required. 

If you can paste your kinesis exit logs, I might be able to help, you may need a different kinesis provider in your yaml file depending on your OS. 

8080 was for the web UI but I think it is deprecated, safest way to observe if localstack is working is to use aws cli to list your streams, databases or any lambdas.

Find the simplified yaml file below. KINESIS_PROVIDER=kinesalite is optional if your kinesis provider is printing an error message. Default port will be 4566 for your physical machine that will talk to local stack edge endpoint in the docker network which will know all the infrastructure behind it
```yaml
version: '3.8'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,s3,sqs
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=localstack-network
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack/data

volumes:
  localstack_data:
networks:
  default:
    name: localstack-network
```
